'use client'
import { useEffect, useState } from 'react'
import { api, getError, sanitizeUser, type ReviewItem, type User } from '@/lib/cinefyl'
import { ErrorState, Guard, LoadingGrid, PageIntro, useAuth } from '@/components/cinefyl-shell'
import { toast } from 'sonner'
function AdminContent() { const { user } = useAuth(); const [stats, setStats] = useState<any>(null); const [users, setUsers] = useState<User[]>([]); const [reviews, setReviews] = useState<ReviewItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load() { setLoading(true); try { const [s, u, r] = await Promise.all([api<any>('/api/admin/stats'), api<any[]>('/api/admin/users'), api<ReviewItem[]>('/api/admin/reviews')]); setStats(s); setUsers(u.map(sanitizeUser)); setReviews(r) } catch (e) { setError(getError(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, []); async function toggle(target: User) { try { const updated = await api<any>(`/api/admin/users/${target._id}`, { method: 'PATCH', body: JSON.stringify({ isAdmin: !target.isAdmin }) }); setUsers((all) => all.map((item) => item._id === target._id ? sanitizeUser(updated) : item)); toast.success('Role updated') } catch (e) { toast.error(getError(e)) } } async function removeUser(target: User) { if (!confirm(`Delete ${target.name}? Their watchlist will also be deleted.`)) return; try { await api(`/api/admin/users/${target._id}`, { method: 'DELETE' }); setUsers((all) => all.filter((item) => item._id !== target._id)); toast.success('User deleted') } catch (e) { toast.error(getError(e)) } } async function moderate(review: ReviewItem, full = false) { if (!confirm(full ? 'Delete this entire watchlist entry?' : 'Clear this rating and review?')) return; try { const result = await api<any>(`/api/admin/reviews/${review._id}${full ? '?full=true' : ''}`, { method: 'DELETE' }); setReviews((all) => full ? all.filter((item) => item._id !== review._id) : all.filter((item) => item._id !== review._id)); toast.success(full ? 'Entry deleted' : 'Review cleared'); void result } catch (e) { toast.error(getError(e)) } }
  if (loading) return <LoadingGrid count={6} />; if (error) return <ErrorState message={error} retry={load} />; return <div className="flex flex-col gap-8"><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Total Users', stats?.totalUsers], ['Rated Films', stats?.totalRatedFilms], ['Average Rating', stats?.averageUserRating], ['Top Rated', stats?.topRatedFilm?.title || 'None']].map(([label, value]) => <div key={String(label)} className="border-[3px] border-ink bg-surface p-5 shadow-[3px_3px_0_#222]"><p className="font-mono text-xs font-bold uppercase text-ink/55">{label}</p><p className="mt-3 truncate font-serif text-3xl font-black">{value}</p></div>)}</section><section className="border-[3px] border-ink bg-surface p-4 shadow-[3px_3px_0_#222]"><h2 className="font-serif text-3xl font-black">User management</h2><div className="mt-4 flex flex-col gap-2">{users.map((target) => <div key={target._id} className="flex flex-col gap-3 border-t-2 border-ink/10 py-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">{target.name}</p><p className="font-mono text-xs text-ink/60">@{target.username} · {target.isAdmin ? 'Admin' : 'Member'}</p></div><div className="flex gap-2"><button disabled={target._id === user?._id} onClick={() => toggle(target)} className="min-h-11 rounded border-2 border-ink px-3 font-mono text-xs font-bold disabled:opacity-35">{target.isAdmin ? 'Demote' : 'Promote'}</button><button disabled={target._id === user?._id} onClick={() => removeUser(target)} className="min-h-11 rounded border-2 border-danger px-3 font-mono text-xs font-bold text-danger disabled:opacity-35">Delete</button></div></div>)}</div></section><section className="border-[3px] border-ink bg-surface p-4 shadow-[3px_3px_0_#222]"><h2 className="font-serif text-3xl font-black">Reviews & ratings</h2>{reviews.length === 0 ? <p className="py-8 font-mono text-sm text-ink/60">No ratings or reviews yet.</p> : <div className="mt-4 flex flex-col gap-3">{reviews.map((review) => <div key={review._id} className="border-t-2 border-ink/10 py-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-serif text-xl font-black">{review.title} {review.userRating && <span className="font-mono text-sm">· {review.userRating}/10</span>}</p><p className="font-mono text-xs text-ink/60">by @{review.user?.username || 'unknown'}</p>{review.reviewText && <p className="mt-2 text-sm italic">“{review.reviewText}”</p>}</div><div className="flex gap-2"><button onClick={() => moderate(review)} className="min-h-11 rounded border-2 border-ink px-3 font-mono text-xs font-bold">Clear Review</button><button onClick={() => moderate(review, true)} className="min-h-11 rounded bg-danger px-3 font-mono text-xs font-bold text-surface">Delete Entry</button></div></div></div>)}</div>}</section></div> }
export default function AdminPage() { return <Guard admin><div className="mx-auto flex max-w-6xl flex-col gap-10 px-4 py-14 md:px-8"><PageIntro eyebrow="Control room" title="Admin Dashboard">Keep the community healthy and see how the Cinefyl shelf is being used.</PageIntro><AdminContent /></div></Guard> }
