'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Search, UserRound } from 'lucide-react'
import { api, getError, initials, sanitizeUser, type User } from '@/lib/cinefyl'
import { EmptyState, ErrorState, LoadingGrid, PageIntro } from '@/components/cinefyl-shell'
export default function UsersPage() { const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load(value = '') { setLoading(true); try { const raw = await api<any[]>(`/api/users/search${value.trim() ? `?q=${encodeURIComponent(value.trim())}` : ''}`); setUsers(raw.map(sanitizeUser)) } catch (e) { setError(getError(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  return <div className="mx-auto flex max-w-6xl flex-col gap-10 px-4 py-14 md:px-8"><PageIntro eyebrow="The community" title="Find Users">Browse public shelves and discover what other cinephiles are watching.</PageIntro><form onSubmit={(e) => { e.preventDefault(); load(query) }} className="mx-auto flex w-full max-w-2xl items-center gap-2 rounded-md border-[3px] border-ink bg-surface px-4 shadow-[3px_3px_0_#222]"><Search className="size-4" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by name or username..." className="min-h-12 w-full border-0 bg-transparent font-mono text-base outline-none focus:ring-0" /></form>{loading ? <LoadingGrid count={6} /> : error ? <ErrorState message={error} retry={() => load(query)} /> : users.length === 0 ? <EmptyState title="User not found" detail="Try a different name or username." /> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{users.map((user) => <Link href={`/user/${encodeURIComponent(user.username)}`} key={user._id} className="flex min-h-24 items-center gap-4 border-[3px] border-ink bg-surface p-4 shadow-[3px_3px_0_#222] transition hover:-translate-y-1"><div className="grid size-14 shrink-0 place-items-center overflow-hidden rounded-md border-2 border-ink bg-ink text-lg font-black text-surface">{user.avatar ? <img src={user.avatar} alt="" className="size-full object-cover" /> : initials(user.name)}</div><div className="min-w-0"><h2 className="truncate font-serif text-xl font-black">{user.name}</h2><p className="flex items-center gap-1 font-mono text-xs text-ink/60"><UserRound className="size-3" /> @{user.username}</p></div></Link>)}</div>}</div>
}
