'use client'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { api, getError, poster, sanitizeUser, type User, type WatchlistItem } from '@/lib/cinefyl'
import { EmptyState, ErrorState, LoadingGrid, PageIntro } from '@/components/cinefyl-shell'
export default function ProfilePage() { const params = useParams<{ username: string }>(); const [user, setUser] = useState<User | null>(null); const [items, setItems] = useState<WatchlistItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  async function load() { setLoading(true); try { const data = await api<any>(`/api/users/${encodeURIComponent(params.username)}`); setUser(sanitizeUser(data.user)); setItems(data.watchlist || []) } catch (e) { setError(getError(e)) } finally { setLoading(false) } }
  useEffect(() => { if (params.username) load() }, [params.username]); if (loading) return <div className="mx-auto max-w-6xl px-4 py-14"><LoadingGrid /></div>; if (error) return <div className="mx-auto max-w-6xl px-4 py-14"><ErrorState message={error} retry={load} /></div>; return <div className="mx-auto flex max-w-6xl flex-col gap-10 px-4 py-14 md:px-8"><PageIntro eyebrow="Public profile" title={user?.name || 'Cinephile'}> @{user?.username} · a public shelf of favorite films and honest reactions.</PageIntro>{items.length === 0 ? <EmptyState title="No films here yet" detail="This shelf is waiting for its first watch." /> : <div className="grid grid-cols-2 gap-5 sm:grid-cols-3 md:grid-cols-4">{items.map((item) => <article key={item._id} className="flex flex-col"><div className="relative aspect-[2/3] overflow-hidden rounded-md border-[3px] border-ink bg-ink/10">{poster(item.poster) ? <img src={item.poster} alt={`${item.title} poster`} className="size-full object-cover" /> : <div className="grid size-full place-items-center p-3 text-center font-serif text-xl font-black">{item.title}</div>}{item.userRating && <span className="absolute right-2 top-2 rounded border-2 border-ink bg-surface px-2 py-1 font-mono text-xs font-bold">{item.userRating}/10</span>}</div><h2 className="mt-3 font-serif text-xl font-bold">{item.title}</h2><p className="font-mono text-xs text-ink/60">{item.year}</p>{item.reviewText && <blockquote className="mt-2 border-l-2 border-ink pl-2 text-sm italic text-ink/70">“{item.reviewText}”</blockquote>}</article>)}</div>}</div>
}
