'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { api, getError, isValidEmail, isValidUsername, sanitizeUser } from '@/lib/cinefyl'
import { useAuth } from './cinefyl-shell'
import { toast } from 'sonner'
export function AuthForm({ mode }: { mode: 'login' | 'register' }) { const router = useRouter(); const { setUser } = useAuth(); const [callbackUrl, setCallbackUrl] = useState('/'); const [form, setForm] = useState({ name: '', username: '', email: '', password: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const register = mode === 'register'; useEffect(() => { setCallbackUrl(new URLSearchParams(window.location.search).get('callbackUrl') || '/') }, [])
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); if (register && form.name.trim().length < 2) return setError('Name must be at least 2 characters'); if (register && !isValidUsername(form.username)) return setError('Username must be 3-15 alphanumeric characters or underscores'); if (!form.email || !form.password) return setError(register ? 'All fields are required' : 'Email and password are required fields'); if (register && !isValidEmail(form.email)) return setError('Invalid email format'); if (register && form.password.length < 6) return setError('Password must be at least 6 characters'); setBusy(true); try { const result = await api<any>(`/api/auth/${register ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(register ? form : { email: form.email, password: form.password }) }); setUser(sanitizeUser(result)); toast.success(register ? 'Welcome to Cinefyl' : 'Welcome back'); router.replace(callbackUrl) } catch (e) { setError(getError(e)) } finally { setBusy(false) } }
  const field = (key: keyof typeof form, label: string, type = 'text', placeholder = '') => <label className="flex flex-col gap-2 font-mono text-xs font-bold">{label}<input required={key === 'email' || key === 'password'} type={type} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} placeholder={placeholder} className="min-h-12 rounded-md border-[3px] border-ink bg-surface px-3 font-mono text-base font-normal outline-none focus:ring-2 focus:ring-ink/30" /></label>
  return <div className="mx-auto flex min-h-[70vh] max-w-md items-center px-4 py-12"><form onSubmit={submit} className="flex w-full flex-col gap-5 border-[3px] border-ink bg-surface p-6 shadow-[5px_5px_0_#222] md:p-8"><div><p className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-ink/55">Cinefyl account</p><h1 className="mt-2 font-serif text-4xl font-black">{register ? 'Join the shelf' : 'Welcome back'}</h1><p className="mt-2 text-ink/65">{register ? 'Create an account and keep your next watch close.' : 'Pick up where your movie night left off.'}</p></div>{register && <>{field('name', 'Name', 'text', 'Your name')}{field('username', 'Username', 'text', 'cinephile_01')}</>}{field('email', 'Email', 'email', 'you@example.com')}{field('password', 'Password', 'password', '••••••••')}{error && <p role="alert" className="border-2 border-danger bg-danger/10 p-3 font-mono text-xs font-bold text-danger">{error}</p>}<button disabled={busy} className="min-h-12 rounded-md bg-ink px-5 font-mono text-sm font-bold text-surface disabled:opacity-50">{busy ? 'Please wait...' : register ? 'Create account' : 'Log in'}</button><p className="text-center font-mono text-xs text-ink/60">{register ? 'Already have an account? ' : 'New to Cinefyl? '}<Link className="font-bold text-ink underline" href={register ? '/login' : '/register'}>{register ? 'Log in' : 'Register'}</Link></p></form></div>
}
