'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import { createContext, useContext, useEffect, useState } from 'react'
import { LogOut, Menu, Search, X } from 'lucide-react'
import { api, getError, initials, sanitizeUser, type User } from '@/lib/cinefyl'
import { toast } from 'sonner'

type AuthContextValue = { user: User | null; loading: boolean; setUser: (user: User | null) => void; logout: () => Promise<void> }
const AuthContext = createContext<AuthContextValue>({ user: null, loading: true, setUser: () => {}, logout: async () => {} })
export function useAuth() { return useContext(AuthContext) }
export function AuthProvider({ children }: { children: React.ReactNode }) {
  const [user, setUser] = useState<User | null>(null); const [loading, setLoading] = useState(true)
  useEffect(() => { api<any>('/api/auth/me').then((value) => setUser(sanitizeUser(value))).catch(() => setUser(null)).finally(() => setLoading(false)) }, [])
  async function logout() { try { await api('/api/auth/logout', { method: 'POST' }); setUser(null); toast.success('Logged out successfully') } catch (error) { toast.error(getError(error)) } }
  return <AuthContext.Provider value={{ user, loading, setUser, logout }}>{children}</AuthContext.Provider>
}

function Avatar({ user }: { user: User }) { return user.avatar ? <img src={user.avatar} alt={`${user.name} avatar`} className="size-8 rounded-md border-2 border-ink object-cover" /> : <span className="grid size-8 place-items-center rounded-md border-2 border-ink bg-ink font-mono text-[10px] text-surface">{initials(user.name)}</span> }
export function Shell({ children }: { children: React.ReactNode }) {
  const { user, loading, logout } = useAuth(); const pathname = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false)
  const nav = [{ href: '/', label: 'Explore' }, { href: '/users', label: 'Find Users' }, ...(user ? [{ href: '/watchlist', label: 'My Watchlist' }] : []), ...(user?.isAdmin ? [{ href: '/admin', label: 'Admin' }] : [])]
  return <div className="min-h-screen bg-canvas text-ink"><header className="sticky top-0 z-40 border-b-[3px] border-ink bg-canvas/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between gap-4 px-4 md:px-8"><Link href="/" className="font-serif text-2xl font-black tracking-[-0.08em]">CINEFYL</Link><nav className="hidden items-center gap-2 md:flex">{nav.map((item) => <Link key={item.href} href={item.href} className={`rounded-md px-3 py-2 font-mono text-xs font-bold transition ${pathname === item.href ? 'border-b-[3px] border-ink' : 'text-ink/65 hover:bg-ink/10 hover:text-ink'}`}>{item.label}</Link>)}</nav><div className="flex items-center gap-2">{loading ? <div className="h-8 w-24 animate-pulse rounded bg-ink/10" /> : user ? <><div className="hidden items-center gap-2 font-mono text-xs font-bold sm:flex"><Avatar user={user} /><span>Logged in as: {user.name}</span></div><button onClick={() => logout()} aria-label="Log out" className="hidden min-h-11 items-center gap-1 rounded-md border-2 border-ink bg-surface px-3 font-mono text-xs font-bold sm:flex"><LogOut className="size-4" /> Logout</button></> : <div className="hidden gap-2 sm:flex"><Link href="/login" className="min-h-11 rounded-md border-2 border-ink bg-surface px-3 py-3 font-mono text-xs font-bold">Login</Link><Link href="/register" className="min-h-11 rounded-md bg-ink px-3 py-3 font-mono text-xs font-bold text-surface">Register</Link></div>}<button aria-label="Open menu" onClick={() => setOpen(!open)} className="grid size-11 place-items-center rounded-md border-2 border-ink bg-surface md:hidden">{open ? <X /> : <Menu />}</button></div></div>{open && <div className="border-t-2 border-ink bg-canvas px-4 py-3 md:hidden"><nav className="flex flex-col gap-1">{nav.map((item) => <Link onClick={() => setOpen(false)} key={item.href} href={item.href} className="rounded-md px-3 py-3 font-mono text-sm font-bold">{item.label}</Link>)}{user ? <button onClick={() => { setOpen(false); logout() }} className="flex items-center gap-2 px-3 py-3 text-left font-mono text-sm font-bold"><LogOut className="size-4" /> Logout</button> : <div className="flex gap-2 px-3 pt-2"><Link href="/login" className="rounded-md border-2 border-ink bg-surface px-3 py-3 font-mono text-xs font-bold">Login</Link><Link href="/register" className="rounded-md bg-ink px-3 py-3 font-mono text-xs font-bold text-surface">Register</Link></div>}</nav></div>}</header><main>{children}</main><footer className="mt-16 border-t-[3px] border-ink"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-4 px-4 py-8 md:flex-row md:px-8"><div className="flex items-center gap-2"><span className="font-serif text-xl font-black tracking-[-0.08em]">CINEFYL</span><span className="font-mono text-xs text-ink/50">© 2026</span></div><div className="flex gap-5 font-mono text-xs font-bold text-ink/60"><span>Privacy</span><span>Terms</span><span>Help</span></div></div></footer></div>
}

export function PageIntro({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: React.ReactNode }) { return <section className="mx-auto flex max-w-3xl flex-col items-center gap-3 text-center"><span className="font-mono text-xs font-bold uppercase tracking-[0.2em] text-ink/55">{eyebrow || 'Cinefyl'}</span><h1 className="font-serif text-4xl font-black tracking-[-0.05em] md:text-6xl">{title}</h1>{children && <p className="max-w-2xl text-lg font-bold leading-relaxed text-ink/75">{children}</p>}</section> }
export function LoadingGrid({ count = 8 }: { count?: number }) { return <div className="grid grid-cols-2 gap-5 md:grid-cols-4">{Array.from({ length: count }).map((_, index) => <div key={index} className="flex flex-col gap-3"><div className="aspect-[2/3] animate-pulse rounded-md border-[3px] border-ink/10 bg-ink/10" /><div className="h-5 animate-pulse rounded bg-ink/10" /><div className="h-3 w-1/3 animate-pulse rounded bg-ink/10" /></div>)}</div> }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <div className="mx-auto flex max-w-md flex-col items-center gap-4 border-[3px] border-ink bg-surface p-8 text-center shadow-[4px_4px_0_#222]"><h2 className="font-serif text-2xl font-black">Something went wrong</h2><p className="font-mono text-xs text-ink/65">{message}</p><button onClick={retry} className="min-h-11 rounded-md bg-ink px-5 font-mono text-xs font-bold text-surface">Try again</button></div> }
export function EmptyState({ title, detail, href }: { title: string; detail?: string; href?: string }) { return <div className="mx-auto flex max-w-md flex-col items-center gap-3 border-[3px] border-ink bg-surface p-8 text-center"><Search className="size-8" /><h2 className="font-serif text-2xl font-black">{title}</h2>{detail && <p className="font-mono text-xs text-ink/65">{detail}</p>}{href && <Link href={href} className="mt-2 rounded-md bg-ink px-5 py-3 font-mono text-xs font-bold text-surface">Explore movies</Link>}</div> }

export function Guard({ children, admin = false }: { children: React.ReactNode; admin?: boolean }) { const { user, loading } = useAuth(); const router = useRouter(); useEffect(() => { if (!loading && !user) router.replace(`/login?callbackUrl=${encodeURIComponent(location.pathname)}`) }, [loading, user, router]); if (loading || !user) return <div className="grid min-h-[60vh] place-items-center font-mono text-sm">Loading session...</div>; if (admin && !user.isAdmin) return <div className="mx-auto grid min-h-[60vh] max-w-xl place-items-center px-4 text-center"><div><h1 className="font-serif text-4xl font-black">Access Denied</h1><p className="mt-3 font-mono text-sm text-ink/65">This area is reserved for Cinefyl admins.</p></div></div>; return <>{children}</> }
