'use client'
import { useState } from 'react'
import { Bookmark, Check, Loader2, Star } from 'lucide-react'
import { addMovie, api, getError, type Movie, type WatchlistItem } from '@/lib/cinefyl'
import { useAuth } from './cinefyl-shell'
import { toast } from 'sonner'
export function MovieCard({ movie, item, onSaved }: { movie: Movie; item?: WatchlistItem; onSaved: (item: WatchlistItem) => void }) {
  const { user } = useAuth(); const [busy, setBusy] = useState(false); const [ratingOpen, setRatingOpen] = useState(false)
  async function save(rating?: number) { if (!user) { toast('Log in to build your watchlist'); return } setBusy(true); try { const response = await addMovie(movie); const saved = 'item' in response ? response.item : response; if (rating) { const updated = await api<WatchlistItem>(`/api/watchlist/${saved._id}`, { method: 'PATCH', body: JSON.stringify({ userRating: rating }) }); onSaved(updated) } else onSaved(saved); toast.success(rating ? `Rated ${rating}/10` : 'Added to watchlist') } catch (error) { toast.error(getError(error)) } finally { setBusy(false); setRatingOpen(false) } }
  return <article className="group flex min-w-0 flex-col"><div className="relative aspect-[2/3] overflow-hidden rounded-md border-[3px] border-ink bg-ink/10 shadow-[3px_3px_0_#222]"><div className="absolute right-2 top-2 z-10 rounded-md border-2 border-ink bg-surface px-2 py-1 font-mono text-xs font-bold">{item?.userRating ? <span className="flex items-center gap-1"><Star className="size-3 fill-warning text-warning" /> {item.userRating}</span> : 'Unrated'}</div>{movie.Poster && movie.Poster !== 'N/A' ? <img src={movie.Poster} alt={`${movie.Title} poster`} className="size-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="grid size-full place-items-center p-4 text-center font-serif text-2xl font-black text-surface">{movie.Title}</div>}<div className="absolute inset-0 flex items-end justify-center gap-2 bg-ink/55 p-3 opacity-0 backdrop-blur-[2px] transition group-hover:opacity-100 focus-within:opacity-100"><button disabled={busy || !!item} onClick={() => save()} className="flex min-h-11 flex-1 items-center justify-center gap-1 rounded-md border-2 border-ink bg-surface px-2 font-mono text-[10px] font-bold text-ink disabled:opacity-70">{busy ? <Loader2 className="size-4 animate-spin" /> : item ? <Check className="size-4" /> : <Bookmark className="size-4" />} {item ? 'Added' : 'Watchlist'}</button><button disabled={busy} onClick={() => setRatingOpen(!ratingOpen)} aria-label={`Rate ${movie.Title}`} className="grid size-11 place-items-center rounded-md border-2 border-ink bg-ink text-surface"><Star className="size-4" /></button></div>{ratingOpen && <div className="absolute inset-x-2 bottom-16 z-20 border-2 border-ink bg-surface p-2"><p className="mb-2 font-mono text-[10px] font-bold">Your rating</p><div className="grid grid-cols-5 gap-1">{Array.from({ length: 10 }, (_, index) => index + 1).map((value) => <button key={value} onClick={() => save(value)} className="grid min-h-9 place-items-center rounded border-2 border-ink font-mono text-xs font-bold hover:bg-secondary">{value}</button>)}</div></div>}</div><h3 className="mt-3 truncate font-serif text-xl font-bold">{movie.Title}</h3><span className="font-mono text-xs font-bold text-ink/60">{movie.Year}</span></article>
}
