'use client'
import { useEffect, useState } from 'react'
import { Trash2 } from 'lucide-react'
import { api, getError, getWatchlist, poster, updateWatchlist, type WatchlistItem } from '@/lib/cinefyl'
import { EmptyState, ErrorState, Guard, LoadingGrid, PageIntro, useAuth } from '@/components/cinefyl-shell'
import { toast } from 'sonner'
function WatchlistContent() { const { user } = useAuth(); const [items, setItems] = useState<WatchlistItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [drafts, setDrafts] = useState<Record<string, { rating: string; review: string }>>({})
  async function load() { if (!user) return; setLoading(true); try { const result = await getWatchlist(user._id); setItems(result); setDrafts(Object.fromEntries(result.map((item) => [item._id, { rating: item.userRating?.toString() || '', review: item.reviewText || '' }]))) } catch (e) { setError(getError(e)) } finally { setLoading(false) } }
  useEffect(() => { load() }, [user])
  async function save(item: WatchlistItem) { const draft = drafts[item._id]; const rating = draft.rating ? Number(draft.rating) : null; if (rating !== null && (!Number.isInteger(rating) || rating < 1 || rating > 10)) return toast.error('Rating must be between 1 and 10'); try { const updated = await updateWatchlist(item._id, { userRating: rating, reviewText: draft.review }); setItems((all) => all.map((entry) => entry._id === updated._id ? updated : entry)); toast.success('Saved changes') } catch (e) { toast.error(getError(e)) } }
  async function remove(id: string) { if (!confirm('Remove this movie from your watchlist?')) return; try { await api(`/api/watchlist/${id}`, { method: 'DELETE' }); setItems((all) => all.filter((item) => item._id !== id)); toast.success('Movie removed') } catch (e) { toast.error(getError(e)) } }
  if (loading) return <LoadingGrid />; if (error) return <ErrorState message={error} retry={load} />; if (!items.length) return <EmptyState title="Your watchlist is empty" detail="Keep your next movie night close." href="/" />; return <div className="grid gap-5 md:grid-cols-2">{items.map((item) => <article key={item._id} className="flex gap-4 border-[3px] border-ink bg-surface p-3 shadow-[3px_3px_0_#222]"><div className="w-24 shrink-0 overflow-hidden rounded border-2 border-ink bg-ink/10 sm:w-32">{poster(item.poster) ? <img src={item.poster} alt={`${item.title} poster`} className="aspect-[2/3] size-full object-cover" /> : <div className="grid aspect-[2/3] place-items-center p-2 text-center font-serif font-bold">{item.title}</div>}</div><div className="flex min-w-0 flex-1 flex-col gap-3"><div><h2 className="truncate font-serif text-2xl font-black">{item.title}</h2><p className="font-mono text-xs text-ink/60">{item.year || 'Year unknown'}</p></div><label className="font-mono text-xs font-bold">Rating (1–10)<input value={drafts[item._id]?.rating || ''} onChange={(e) => setDrafts({ ...drafts, [item._id]: { ...drafts[item._id], rating: e.target.value } })} type="number" min="1" max="10" className="mt-1 min-h-11 w-full rounded border-2 border-ink bg-canvas px-2 font-mono text-base" /></label><label className="font-mono text-xs font-bold">Review<textarea maxLength={1000} value={drafts[item._id]?.review || ''} onChange={(e) => setDrafts({ ...drafts, [item._id]: { ...drafts[item._id], review: e.target.value } })} className="mt-1 min-h-20 w-full rounded border-2 border-ink bg-canvas p-2 font-mono text-base" placeholder="What stayed with you?" /></label><div className="mt-auto flex gap-2"><button onClick={() => save(item)} className="min-h-11 flex-1 rounded bg-ink px-3 font-mono text-xs font-bold text-surface">Save</button><button onClick={() => remove(item._id)} aria-label={`Remove ${item.title}`} className="grid min-h-11 min-w-11 place-items-center rounded border-2 border-ink"><Trash2 className="size-4" /></button></div></div></article>)}</div>
}
export default function WatchlistPage() { return <Guard><div className="mx-auto flex max-w-6xl flex-col gap-10 px-4 py-14 md:px-8"><PageIntro eyebrow="Your collection" title="My Watchlist">A living shelf for films you want to remember, revisit, or finally make time for.</PageIntro><WatchlistContent /></div></Guard> }
